package be.leukspul.arc.manager.admin;

import be.leukspul.arc.library.model.PcTemplate;
import be.leukspul.arc.server.GameClient;
import be.leukspul.arc.server.shard.Shard;
import be.leukspul.data.ecs.Entity;
import be.leukspul.data.ecs.component.*;

import java.util.List;
import java.util.Random;

public class AdminSpawn extends AdminCommand {

    public AdminSpawn(String input) {
        super(input);
    }

    @Override
    public void execute(Entity admin) {
        Shard shard = admin.get(RefShard.class).Shard;
        PcTemplate randomTemplate = shard.lib().PcTemplates().random();
        Entity spawn = new Entity(shard.nextID());
        spawn.position().copy(admin.position());
        Skills skills = new Skills();

        boolean isBoy = random.nextBoolean();
        Avatar avatar = new Avatar(randomTemplate, isBoy ? 0 : 1, 0, 0, 0);
        Vitals vitals = new Vitals(100, 100);
        Attributes attributes = new Attributes(99, 99, 99, 99, 99, 99);
        RefShard refShard = new RefShard(shard);
        RefTask refTask = new RefTask();
        refTask.List = baseTasks -> baseTasks.addAll(shard.entityManager().entityTasks(spawn));
        avatar.Name = isBoy ? randomMaleName() : randomFemaleName();
        avatar.Walking = random.nextBoolean();
        spawn.add(avatar);
        spawn.add(vitals);
        spawn.add(attributes);
        spawn.add(refShard);
        spawn.add(skills);
        spawn.add(refTask);
        List<GameClient> clients = shard.clients(spawn.position(), 20000);
        for (GameClient client : clients) {
            client.visibility().seen(spawn);
        }
        shard.registerEntity(spawn);
    }

    private String randomMaleName() {
        return randomMaleNames[random.nextInt(randomMaleNames.length)];
    }

    private String randomFemaleName() {
        return randomFemaleNames[random.nextInt(randomFemaleNames.length)];
    }

    private static String [] randomMaleNames = {
            "Bart Berke",
            "Napoleon Nipp",
            "Guillermo Gallup",
            "Clifton Crossett",
            "Aaron Algarin",
            "Tyson Thibault",
            "Jonah Johns",
            "Sanford Sylvain",
            "Everette Empey",
            "Elbert Enloe",
            "Louis Lien",
            "Dustin Degnan",
            "Blake Belote",
            "Zachery Zarrella",
            "Jacob Jayne",
            "Eldridge Etzel",
            "Erik Eichelberger",
            "Mauro Mensch",
            "Elwood Endo",
            "Charles Canty",
            "Tuan Turney",
            "Mohamed Mirsky",
            "Eugenio Eggen",
            "Gary Gillian",
            "Justin Jeter",
            "Dorian Duprey",
            "Lucas Lofland",
            "Sherwood Sheard",
            "Ollie Ohm",
            "Al Aguillon",
            "Adolfo Ashworth",
            "Devon Dankert",
            "Damien Denis",
            "Wilbert Whitby",
            "Rosario Reel",
            "Chas Cap",
            "Timmy Toy",
            "Cary Cermak",
            "Lamont Leday",
            "Abram Altamirano",
            "Dylan Doby",
            "Kenneth Kinchen",
            "Cornell Cardona",
            "Gus Grumbles",
            "Jefferey Jiggetts",
            "Keith Killgore",
            "Emmitt Ek",
            "Les Linn",
            "Bill Blubaugh",
            "Dong Dea",
            "Robby Ragon",
            "Irwin Izzi",
            "Hoyt Holter",
            "Werner Wellner",
            "Daren Delisa",
            "Darryl Domenico",
            "Gilbert Galey",
            "Miguel Midgley",
            "Daniel Derrico",
            "Dusty Dunnington",
            "Stephen Swisher",
            "Gaston Gurrola",
            "Marvin Marchan",
            "Faustino Fix",
            "Fabian Fortin",
            "Ellsworth Estrella",
            "Hayden Hallinan",
            "Boyd Brawley",
            "Jefferey Johnsen",
            "Kennith Kampf",
            "Rigoberto Roquemore",
            "Damian Drennen",
            "Donn Dalley",
            "Reed Roundtree",
            "Rodney Recinos",
            "Alden Aubry",
            "Edmond Etheredge",
            "Giovanni Goldsberry",
            "Marc Miyamoto",
            "Rene Rittenberry",
            "Dewitt Durrah",
            "Gerard Garlow",
            "Sandy Schleusner",
            "Tory Temples",
            "Lionel Luick",
            "Lyle Liberto",
            "Adrian Alward",
            "Sydney Sanks",
            "Clement Coffin",
            "Milton Mahone",
            "Anderson Andreas",
            "Ray Raimondi",
            "Hugh Holtzclaw",
            "Deangelo Depew",
            "Felipe Foshee",
            "Shawn Salomone",
            "Philip Prieto",
            "Steven Santana",
            "Everett Erdman",
            "Keven Kopecky",
            "Marvin Mendell",
            "Jeffery Jenson",
            "Elvin Eastin",
            "Long Leroux",
            "Marco Minnick",
            "Alexander Atchison",
            "Morton Mattera",
            "Curtis Capp",
            "Markus Mean",
            "Huey Hymer",
            "Wilfred Wile",
            "Brain Blunk",
            "Lamont Lewis",
            "Will Westlund",
            "Truman Tillmon",
            "Rob Reidhead",
            "Fernando Freels",
            "Bruce Bratt",
            "Kurtis Kaye",
            "Micheal Milewski",
            "Guy Goodrow",
            "Eduardo Elliff",
            "George Gale",
            "Rosendo Ramsden",
            "Kristopher Kratky",
            "Abdul Alford",
            "Chance Capone",
            "Johnnie Jaime",
            "Tracy Taormina",
            "Murray Macdougall",
            "Cyrus Coaxum",
            "Leland Leonhardt",
            "Tad Tao",
            "Weston Whaley",
            "Ruben Rotter",
            "Lawerence Lipsky",
            "Antony Allums",
            "Wiley Wing",
            "Benito Blazier",
            "Erin Eyman",
            "Isaias Inskeep",
            "Cory Chabolla",
            "Jorge Jiron",
            "Al Allaire",
            "Rod Riffle",
            "Del Derossett",
            "Humberto Henline",
            "Marcel Mertens",
            "Brian Benny",
            "Emanuel Escalona",
            "Jefferey Jump",
            "Marco Magnuson",
            "Napoleon Niel",
            "Byron Buker",
            "Tim Tse",
            "Dexter Dorothy",
            "Ervin Emigh",
            "Chase Crittendon",
            "Bo Bezio",
            "Christian Chon",
            "Armando Almendarez",
            "Devin Dickison",
            "Walker Winebarger",
            "Paul Pottinger",
            "Curtis Capehart",
            "Joan Jesus",
            "Arlie Auton",
            "Dave Deeb",
            "Craig Cooke",
            "Arnold Appleton",
            "Marcus Mcpeek",
            "Chester Cullison",
            "Chong Campa",
            "Hai Halford",
            "Leland Longmire",
            "Carmine Cheyne",
            "Kelvin Koenig",
            "Teddy Tooley",
            "Jarrod Jo",
            "Irvin Isaacs",
            "Kyle Kinard",
            "Hank Hollier",
            "Randell Ruhl",
            "Denver Deyoe",
            "Jerrell Johnosn",
            "Donald Dennison",
            "Rudy Redondo",
            "Clay Click",
            "Milan Maust",
            "Courtney Chou",
            "Robin Robbs",
            "Manual Mineau",
            "Carol Cobian",
            "Shirley Stejskal",
            "Jerold Joshua",
            "Eldon Engstrom",
            "Raymond Rother",
            "Israel Ivery",
            "Gordon Galiano",
            "Dorsey De"
    };

    private static String [] randomFemaleNames = {
            "Eda Eynon",
            "Lillia Lebel",
            "Lorina Laidlaw",
            "Tish Theberge",
            "Madeleine Monteith",
            "Carma Cowgill",
            "Cherry Cheers",
            "Alline Alfonso",
            "Aleta Audet",
            "Sharell Saeger",
            "An Acosta",
            "Christal Chairez",
            "Natalie Nunemaker",
            "Princess Philbrook",
            "Li Lucia",
            "Ethelyn Espino",
            "Sona Shue",
            "Lieselotte Luellen",
            "Francene Folger",
            "Elfriede Ensminger",
            "Kami Kildow",
            "Jolanda Jimenes",
            "Georgiann Goetzinger",
            "Maud Mishler",
            "Ellamae Eisen",
            "Golda Greiner",
            "Katerine Karlin",
            "Emelda Echeverria",
            "Evette Elgin",
            "Edris Eckles",
            "Pura Puryear",
            "Keshia Knick",
            "Mikaela Malchow",
            "Marjory Mckean",
            "Carolynn Corral",
            "Cara Centeno",
            "Tynisha Traynor",
            "Taina Toal",
            "Adrianne Ayoub",
            "Penni Prieto",
            "Amparo Amey",
            "Chery Coyle",
            "Tarsha Terranova",
            "Antonina Atteberry",
            "Lakeisha Lard",
            "Bea Bruton",
            "Gwyn Glance",
            "Shandra Schranz",
            "Sandie Short",
            "Diedra Dibernardo",
            "Glinda Geter",
            "Elfrieda Eisenbarth",
            "Narcisa Noon",
            "Jennie Jamal",
            "Winifred Wherry",
            "Maureen Mertens",
            "Erminia Ernst",
            "Caprice Cortina",
            "Regenia Rehberg",
            "Cari Cape",
            "Shandra Swearengin",
            "Maryalice Maese",
            "Jeniffer Jasmin",
            "Traci Theriault",
            "Tiara Townsley",
            "Desirae Deems",
            "Tatum Tseng",
            "Divina Dake",
            "Verdie Vanbeek",
            "Wanita Waldroup",
            "Mafalda Mclester",
            "Keely Koop",
            "Liana Locascio",
            "Garnett Gillman",
            "Debby Ducan",
            "Gabriele Gleeson",
            "Dionna Defelice",
            "Vanetta Venuti",
            "Cara Connon",
            "Lavina Lachapelle",
            "Camelia Cavaliere",
            "Emilia Ervin",
            "Magda Mahoney",
            "Janna Jaillet",
            "Yer Yokota",
            "Wava Weddell",
            "Leana Laseter",
            "Kenda Kerfien",
            "Guillermina Greco",
            "Carola Clemente",
            "Dede Deweese",
            "Ruth Reeder",
            "Elva Earles",
            "Michaele Miah",
            "Tammara Torrey",
            "Susan Sobieski",
            "Thresa Thiry",
            "Shirely Schurr",
            "Sonya Sally",
            "Velia Villeda",
            "Heidi Hockett",
            "Savanna Skow",
            "Evelin Erb",
            "Quyen Quevedo",
            "Patsy Prager",
            "Helen Helsel",
            "Margarite Mote",
            "Kia Koenig",
            "Stephany Shanley",
            "Belinda Brink",
            "Orpha Olds",
            "Justina Jamal",
            "Janice Jansky",
            "Twyla Tarkington",
            "Bella Barbe",
            "Ellena Elgin",
            "Gretchen Garnett",
            "Danita Duer",
            "Stephenie Satterthwaite",
            "Merlene Markey",
            "Michiko Magruder",
            "Britteny Bulger",
            "Mui Moise",
            "Echo Earle",
            "Karleen Klotz",
            "Adela Alli",
            "Octavia Obregon",
            "Karissa Kerfien",
            "Kalyn Kloss",
            "Henrietta Haugh",
            "Kaitlin Khang",
            "Cleora Crume",
            "Lauralee Lavallie",
            "Barabara Berwick",
            "Willodean Woldt",
            "Antonina Appell",
            "Akilah Arneson",
            "Tanna Tumlinson",
            "Maryln Maggio",
            "Matha Moffitt",
            "Fran Fallen",
            "Pearle Parada",
            "Asuncion Armbruster",
            "Roni Renfrow",
            "Terina Teel",
            "Ladawn Landes",
            "Janie Jurado",
            "Moira Manley",
            "Starla Scharf",
            "Muriel Mcfatridge",
            "Gemma Garland",
            "Bok Brashier",
            "Summer Sneller",
            "Lanelle Lasher",
            "Fatima Frandsen",
            "Bernardina Bartmess",
            "Melodi Mckamey",
            "Nella Nolasco",
            "Amanda Aguinaga",
            "Rubye Righter",
            "Jacquiline Janssen",
            "Elayne Ells",
            "Linn Lanning",
            "Vergie Voltz",
            "Vickey Verne",
            "Merissa Marler",
            "Cammie Copen",
            "Denisse Dambrosio",
            "Darcey Duden",
            "Teressa Thomson",
            "Natalia Nagle",
            "Cherlyn Cotten",
            "Angelita Accardi",
            "Glennis Gautreaux",
            "Brigitte Blust",
            "Georgina Gafford",
            "Nettie Neher",
            "Harmony Heatley",
            "Neoma Nakayama",
            "Cherie Carrick",
            "Kenyatta Kolb",
            "Tegan Tolley",
            "Shery Sheldon",
            "Gina Grippo",
            "Louann Lanahan",
            "Tamika Tripodi",
            "Trista Thomson",
            "Flossie Fortino",
            "Maritza Monge",
            "Dorris Dawdy",
            "Alline Abner",
            "Catherine Caballero",
            "Tatyana Tatom",
            "Georgianne Gremillion",
            "Lieselotte Litman",
            "Willia Willis",
            "Magda Mcilvain",
            "Roseline Rossetti",
            "Tanika Tracy",
            "Saran Schweizer"
    };

    private static Random random = new Random();

}
